spring:
  profiles:
    active:    - local
    
---

spring:
  profiles:
  - local
  
  devtools:
    livereload:      enabled: true
  
  mvc:
    view:
      prefix: "/WEB-INF/views"
      suffix: ".jsp"

  datasource:    url: jdbc:mysql://localhost:3306/monsh_mall?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  session:
    jdbc:
      initialize-schema: always

  servlet:    multipart:      enabled: true

server:  port: 8080
  tomcat:    uri-encoding: UTF-8
    
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
    jsp:
      init-parameters:        development: true
    session:
      timeout: 7200
      
  error:
    whitelabel:
      enabled: false
      
mybatis:
  type-aliases-package: tk.monsh.springbootpractice.domain
  mapper-locations: mapper/**/*.xml

logging:
  config: classpath:logback-spring.xml